on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

name: "Flatpak Qt6"

jobs:
  flatpak:
    name: "Flatpak Builder with Qt 6.4 and Poppler"
    runs-on: ubuntu-22.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-6.4
      options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build flatpak
      uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: beamerpresenter-qt6.flatpak
        manifest-path: packaging/io.github.beamerpresenter.beamerpresenter-qt6.yml
        arch: x86_64
        cache-key: flatpak-builder-${{ github.sha }}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          beamerpresenter-qt6.flatpak
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
