name: "package Ubuntu 22.04 Qt6 MuPDF"

on:
  # First try this out and run it only manually.
  workflow_dispatch
  # This is the default config:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  # The branches below must be a subset of the branches above
  #  branches: [ main ]

env:
  VERSION: 0.2.2
  MUPDF_VERSION: 1.19.1

jobs:
  package:
    name: Package
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download and unpack MuPDF
      run: |
        wget -q https://mupdf.com/downloads/archive/mupdf-$MUPDF_VERSION-source.tar.xz
        sha256sum -c - <<< "b5eac663fe74f33c430eda342f655cf41fa73d71610f0884768a856a82e3803e mupdf-$MUPDF_VERSION-source.tar.xz"
        tar -xf mupdf-$MUPDF_VERSION-source.tar.xz

    - name: Install Dependencies
      run: >
        sudo apt-get install -y --no-install-recommends
        cmake
        zlib1g-dev
        libgumbo-dev
        libfreetype-dev
        freeglut3-dev
        libharfbuzz-dev
        libjpeg-dev
        libopenjp2-7-dev
        libjbig2dec0-dev
        qt6-multimedia-dev
        libqt6opengl6-dev
        libgl1-mesa-dev
        qt6-tools-dev
        qt6-tools-dev-tools
        qt6-l10n-tools

    - name: Build MuPDF
      run : |
        cd "mupdf-$MUPDF_VERSION-source"
        rm -rf thirdparty/{freeglut,freetype,harfbuzz,jbig2dec,libjpeg,openjpeg,zlib}
        CFLAGS+=' -fPIC -ffat-lto-objects'
        CXXFLAGS+=' -fPIC'
        USE_SYSTEM_LIBS='yes'
        XCFLAGS+=' -DTOFU -DTOFU_CJK -DTOFU_SIL -DFZ_ENABLE_JS=0'
        export CFLAGS CXXFLAGS USE_SYSTEM_LIBS XCFLAGS
        make build=release libs

    - name: Configure
      run: >
        cmake
        -B build_dir
        -DUSE_MUPDF=ON
        -DUSE_POPPLER=OFF
        -DUSE_QTPDF=OFF
        -DUSE_EXTERNAL_RENDERER=OFF
        -DUSE_MUJS=ON
        -DUSE_GUMBO=ON
        -DMUPDF_LIB_PATH="$(pwd)/mupdf-$MUPDF_VERSION-source/build/release/libmupdf.a"
        -DMUPDF_THIRD_LIB_PATH="$(pwd)/mupdf-$MUPDF_VERSION-source/build/release/libmupdf-third.a"
        -DMUPDF_INCLUDE_DIR="$(pwd)/mupdf-$MUPDF_VERSION-source/include"
        -DUSE_TRANSLATIONS=ON
        -DQT_VERSION_MAJOR=6
        -DQT_VERSION_MINOR=2
        -DMARK_AS_SMALL=ON
        -DGIT_VERSION=OFF
        -DCMAKE_BUILD_TYPE='Release'
        -DCPACK_GENERATOR='DEB;'
        -DCMAKE_INSTALL_PREFIX='/usr'
        -DCMAKE_INSTALL_SYSCONFDIR='/etc'
        -DINSTALL_LICENSE=OFF

    - name: Build
      run: cmake --build build_dir

    - name: Package
      run: cpack --config build_dir/CPackConfig.cmake

    - name: Archive debian package
      uses: actions/upload-artifact@v2
      with:
        name: beamerpresenter-mupdf-small-$VERSION-qt6-x86_64.deb
        path: /home/runner/work/BeamerPresenter/BeamerPresenter/beamerpresenter-mupdf-small-$VERSION-qt6-x86_64.deb
